### ISSUE TITLE
Support for authentication for helm repos

### ISSUE THREAD

**Issue by zkutasi** [shteou/helm-dependency-fetch#18]
Hi,

I have found your tool by searching for a solution to the same problem, that helm dependency handling is so slow it actually is unusable. Your tool works well for passwordless repos for me, but we have some repos which we need a username/password, and it seems that is not handled or at least I do not know how to make it work. These credentials are put into the helm repository.yaml
If you could maybe point me into a right direction, or you could add it, it would be really helpful.

Hope this is easy enough for you :), unfortunately I know nothing about golang.
Thanks for this little tool :).

**Comment by shteou** [comment]
@zkutasi hey, I'll try and take a look at this :+1:
I'm glad you like the tool, this makes me happy!

**Comment by shteou** [comment]
@zkutasi I've pushed a new version with support for this but haven't yet tagged/released it.
If you'd like to give it a go now you can build the application (with a working go installation, just `go build cmd/fetch/main.go` and use the resulting binary).

Otherwise I'll get it tested on Windows/Mac before releasing.

**Comment by shteou** [comment]
The latest release is now available: https://github.com/shteou/helm-dependency-fetch/releases/tag/v1.1.0

Can you let me know if this satisfies the issue? If so I'll close it off. Cheers!

**Comment by zkutasi** [comment]
Thanks @shteou , it works perfectly :). Thanks for adding this so quickly. Happy Holidays!
